name: Docker

on:
  schedule:
    - cron: '23 11 * * *'
  push:
    branches: [ "main" ]
    # 发布语义版本标签为 releases。
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  # 如果为空，则使用 docker.io 作为 Docker Hub
  REGISTRY: ghcr.io
  # github.repository 作为 <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # 用于完成身份验证挑战的权限
      # 与 sigstore/fulcio 配合使用时，在 PR 之外运行。
      id-token: write

    steps:
      - name: 检出仓库
        uses: actions/checkout@v3

      # 安装 cosign 工具，除非是 PR
      # https://github.com/sigstore/cosign-installer
      - name: 安装 cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@6e04d228eb30da1757ee4e1dd75a0ec73a653e06 #v3.1.1
        with:
          cosign-release: 'v2.1.1'

      # 设置 BuildKit Docker 容器构建器，以便能够构建
      # 多平台镜像并导出缓存
      # https://github.com/docker/setup-buildx-action
      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      # 登录到 Docker 注册表，除非是 PR
      # https://github.com/docker/login-action
      - name: 登录到注册表 ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 提取 Docker 的元数据（标签，标签）
      # https://github.com/docker/metadata-action
      - name: 提取 Docker 元数据
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # 使用 Buildx 构建和推送 Docker 镜像（在 PR 上不推送）
      # https://github.com/docker/build-push-action
      - name: 构建和推送 Docker 镜像
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags | replaceAll('sha256:', '') }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 对生成的 Docker 镜像摘要进行签名，除非是 PR。
      # 仅当 Docker 存储库为 public 时，才将数据写入公共 Rekor 透明日志，以避免泄露数据。
      # 如果要为私有镜像发布透明数据，传递 --force 到下面的 cosign。
      # https://github.com/sigstore/cosign
      - name: 对发布的 Docker 镜像进行签名
        if: ${{ github.event_name != 'pull_request' }}
        env:
          # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        # 此步骤使用身份令牌在 sigstore 社区的 Fulcio 实例上生成短暂证书。
        run:  echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

